from gym_mod.gymenvs.gym_walker_s2r import GymWalker, GymWalkerBackwards
from gym_mod.gymenvs.gym_walker_s2r_color_change import GymWalkerColor, GymWalkerColorNoBackground, GymWalkerDM
from gym_mod.gymenvs.dynamics_change import GymInvertedPendulumWeight, GymHopperWeight, GymHalfCheetahArmature, GymWalkerWeight
from gym_mod.gymenvs.visual_change import GymHalfCheetahColor, GymHopperColor, GymHopperColor2, \
    GymInvertedPendulumColor, GymInvertedPendulumBackground, GymInvertedPendulumViewpoint, GymReacherColor, GymReacher, GymHalfCheetahDM
from gym_mod.gymenvs.all_change import GymInvertedPendulumWeightColor, GymInvertedPendulumWeightColor2, GymInvertedPendulumWeightColor3, GymInvertedPendulumDM, GymHopperWeightColor, GymFetchReachEnv, GymFetchReach2Env, GymWalkerWeightColor
from gym_mod.gymenvs.easy_env import GymHalfCheetahEasy, GymInvertedPendulumEasy, GymWalkerEasy
